### ISSUE TITLE
Invalid authentication data

### ISSUE THREAD

**Issue by CStan77** [JurajNyiri/pytapo#113] opened 2024-05-09 09:47 UTC
Good morning,
I have my C200 and C210 cameras which have just been updated.
unfortunately the script to manage them locally no longer works :-(

**with firmware 1.3.6 Build 230424**
```
# python3 ptz_c200.PY -ip 192.168.1.37 -u tapoadmin -p ********* -port 554 -i -v
  [DEBUG] : Namespace(ip='192.168.1.37', port=554, user='tapoadmin', password='*********', move=None, info_device=True, cmd=None, v=True)

  [DEBUG] : {'device_info': {'basic_info': {'device_type': 'SMART.IPCAMERA', 'device_model': 'C200', 'device_name': 'C200 1.0', 'device_info': 'C200 1.0 IPC', 'hw_version': '1.0', 'sw_version': '1.3.6 Build 230424 Rel.77225n(4555)', 'device_alias': 'Tapo_Camera_D5F1', 'avatar': 'camera c200', 'longitude': 0, 'latitude': 0, 'has_set_location_info': 0, 'features': '3', 'barcode': '', 'mac': 'C0-**-**-**-D5-F1', 'dev_id': '80218821610803A93915C726068067F11DD36C2B', 'oem_id': '8902D2F34FCE407721DE92F5759839C2', 'hw_desc': '48574445534300000000000000000001'}}}

 Information de la camera :
  ALIAS      : Tapo_Camera_D5F1
  MODEL      : C200
  VERSION    : 1.0
  FIRMWARE   : 1.3.6 Build 230424 Rel.77225n(4555)
  ADR. MAC   : C0-**-**-**-D5-F1
  ADR. IP    : 192.168.1.37
  DATE HEURE : 2024-05-09 10:31:16
  NB. PRESET : 1 {'1': 'Home'}
  DISTORTION : True
  LED ALIM   : Eteinte
  MODE NUIT  : auto
```

**with firmware 1.3.9**

```
# python3 ptz_c200.PY -ip 192.168.1.37 -u tapoadmin -p ********* -port 554 -i -v
  [ERREUR] : Connexion impossible => Invalid authentication data
```

**with your code Tapocloud**
```
        try:
            tapo = Tapo(host, "admin", password_cloud)
            request = tapo.getBasicInfo()
            print(request)
        except Exception as e:
            print("  [ERREUR] : Connexion impossible => %s\n" % (e))
            pass

        try:
            tapo = Tapo(host, user, password)

            request = tapo.getBasicInfo()
            print(request)            
        except Exception as e:
            print("  [ERREUR] : Connexion impossible => %s\n" % (e))
            pass
```

Output :
```
# python3 ptz_c200.PY --debug
  [ERREUR] : Connexion impossible => Invalid authentication data

  [ERREUR] : Connexion impossible => Invalid authentication data
```

**Comment by JurajNyiri** [comment] 2024-05-09 09:48
See https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551

**Comment by JurajNyiri** [comment] 2024-05-09 09:49
Duplicate of https://github.com/JurajNyiri/pytapo/issues/109

**Closed by JurajNyiri** 2024-05-09 09:49 UTC

**Comment by CStan77** [comment] 2024-05-09 10:05
I didn't read to the end...
as much for me

Well, there’s not much to do, other than wait.

**Comment by JurajNyiri** [comment] 2024-05-09 10:06
There are workarounds available to get the camera working right now described in that issue.

**Comment by CStan77** [comment] 2024-05-09 10:12
I'm going to reflash an old firmware
